apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: kubernetes
    repoURL: "https://github.com/springsandbox/infra"
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true